[project]
name = "yt-dlp-gui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pip>=25.3",
    "pyside6>=6.9.0",
    "qtawesome>=1.4.0",
    "yt-dlp>=2025.12.8",
]
